name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: 
  push:
    branches:
      - main
  workflow_dispatch:  
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Log in to container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{secrets.GHCR_TOKEN}}
          
      - name: Build docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ghcr.io/frecapg7/vakeo-api:latest
          file: DockerFile
          
      
